name: Send WhatsApp Message Every Hour

on:
  schedule:
    - cron: '0 * * * *'  # This runs at the start of every hour

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Set the version you want

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twilio

      - name: Run script
        run: |
          python app.py  # Your Python script name
